### ISSUE TITLE
xcode编译失败

### ISSUE THREAD

**Issue by chinafelix** [pengVc/lantu-union-pay#1]
![image](https://user-images.githubusercontent.com/20641047/59246710-b811f380-8c4f-11e9-837c-ce99b3d6d6d2.png)

我试验了一下两种方法，都无效：
1.添加c++库：libc++.tdb；
2.修改编译配置，Apple Clang - Language 标签下的 C Language Dialect属性值修改为 Compiler Default、Compile Sources As属性值修改为According to File Type，Apple Clang - Language-C++ 标签下的C++ Language Dialect 和 C++ Standard Library 属性值修改为 Compiler Default

**Comment by pengVc** [comment]
看来是在模拟器上遇上的错误, 虽然不知道最后你是如何解决的.

但我这儿能确定银联支付控件(ios@3.3.11), 能够在模拟器上正常运行 😀
